#:kivy 2.0.0
    
<Converture>:
    Button:
        text: 'Converture'
        color: 0, 1, 1, 1
        background_color: 1, 1, 0, 1
        pos: root.x + 250, root.y + 280
        size_hint: None, None
        size: 200, 50
        
    TextInput:
        size_hint: None, None
        size: 200, 30
        pos: root.x + 250, root.y + 350
        
    Label:
        text: 'Hello world !'
        pos: root.x + 255, root.y + 400 